version: "3.8"
services:
  traefik:
    image: traefik:latest
    command:
      - "--api=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/dynamic"
      - "--providers.file.watch=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=red@redisa.dev"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./dynamic:/dynamic"
      - "./letsencrypt/acme.json:/letsencrypt/acme.json"

    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
